### ISSUE TITLE
How do I install? 

### ISSUE THREAD

**Issue by ConvexTlc97** [Rem0o/FanControl.ADLX#24]
Instructions are vague and confusing. The AppVeyor link leads to nothing, no download there. What files outside what I assume is 3 DLL files I put in the pluggins folder in fan control do nothing so not sure if I am not installing properly or the pluggin doesn work for my rx 6000 series gpu.

**Comment by levouh** [comment]
@Rem0o it looks like AppVeyor only keeps build artifacts around for 1 month, and they are no longer visible on the link in the README just FYI. Either need a new build to be triggered, or do something like upload them as a release in Github.

**Comment by Rem0o** [comment]
I didn't make a release because the plugin still have a few problems and bugs to be used blindly by regular users.   You can always compile the solution, there is nothing fancy required to do so, just Visual Studio..   I can trigger a appveyor build, but until I get a new AMD GPU or someone else takes this project in hand, this plugin is not ready to be used by the general public.

**Comment by niky45** [comment]
hello, I get this is not ready for the general public, however, I would still like to try it and maybe give some feedback (I'm very good at finding bugs and edge cases). 

however, the appveyor site is empty, and "just build it using visual studio" is not enough for me to get started. could you either trigger a build, or at least provide some rough instructions on how to build it? I have visual studio code up and running. 

on a different note, AMD GPU fans used to work (without the need for plugins) after a driver update roughly half a year ago (IIRC). I have a 6650xt.

**Comment by Rem0o** [comment]
https://ci.appveyor.com/project/Rem0o/fancontrol-adlx/build/artifacts

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.ADLX/releases/tag/V0.1
